server:
  port: 555

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  redis:
    database: 0
    #host: 106.14.195.35
    host: 192.168.0.217
    #password: azkj201918
  data:
    mongodb:
      uri: mongodb://106.14.195.35:27017/comment
  transaction:
    rollback-on-commit-failure: true

