server:
  port: 555

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  redis:
    database: 0
    host: 106.14.195.35
    #host: 192.168.0.217
    #host: localhost
    password: azkj201918
    #password:
  data:
    mongodb:
      uri: mongodb://106.14.195.35:27017/comment
      #uri: mongodb://localhost:27017/discuss
  transaction:
    rollback-on-commit-failure: true

